[[language]]
name = "perl"
auto-format = true
formatter = { command = "perltidy" }
file-types = ["pm", "pl", "cgi", "t"]

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c","h"]
comment-token = "//"
language-servers = [ "clangd" ]
indent = { tab-width = 4, unit = "  " }
auto-format = true
formatter = { command = "clang-format" }
